apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-web-app
  namespace: argocd
spec:
  destination:
    namespace: defaut
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/pierorospigliosiremark/argocd-practice.git
    path: simple-web
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
